[pytest]
markers =
    smoke: Pruebas criticas y rapidas
    regression: Pruebas de regresion completa
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v --html=reports/reporte.html --self-contained-html
